# https://github.com/jeffreytse/jekyll-theme-yat/?tab=readme-ov-file#remote-theme-method-with-github-pages
remote_theme: "jeffreytse/jekyll-theme-yat"

# https://github.com/jeffreytse/jekyll-theme-yat/blob/master/_config.yml
title: This is draft!
email: 
author: Quantum Physical Chemistry Laboratory, Yokohama City University
copyright: "Â© 2024 {author}"
description: "description description description description description description description description description description"
# favicon: "./favicon.svg"
night_mode: "manual"
brand_color: "#8FC231"

defaults:
  home:
    heading: "International Workshop on Theoretical and Computational Chemistry 2024"
    subheading: "January XXth, 2024 in Kanazawa-Hakkei Campus of Yokohama City University"
    banner: "./home.jpg" # https://www.yokohama-cu.ac.jp/brandguide/materialdata/photodata/index.html

banner:
  # video: null             # Video banner source
  # loop: true              # Video loop
  # volume: 0               # Video volume (100% is 1.0)
  # start_at: 0             # Video start time
  # image: "Your image url" # Image banner source
  # opacity: 1.0            # Banner opacity (100% is 1.0)
  # background: "#95C8BF"   # Banner background (Could be a image)
  # height: "640px"         # Banner default height
  # min_height: null        # Banner minimum height
  # heading_style: null     # Custom heading style (e.g. "font-weight: bold; text-decoration: underline")
  # subheading_style: null  # Custom subheading style (e.g. color: gold)

code_badge:
  enabled: "true"
  color: "#fff"
  background_color: "#EA5A47"
  text_transform: "uppercase"  # ("uppercase", "lowercase", "capitalize")

# header_pages: []
# translate_langs: []
translate_langs:
  - lang: ja
    img: https://cdn.countryflags.com/thumbs/japan/flag-400.png
    text: Japanese

  - lang: th
    img: https://cdn.countryflags.com/thumbs/thailand/flag-400.png
    text: Thai

  - lang: en
    img: https://cdn.countryflags.com/thumbs/united-states-of-america/flag-400.png
    text: English

  - lang: fr
    img: https://cdn.countryflags.com/thumbs/france/flag-400.png
    text: French
